spring:
  application:
    name: medical-questionnaire
  jackson:
    property-naming-strategy: SNAKE_CASE
  data:
    mongodb:
      uri: mongodb+srv://manual-case-study:123qwe@ganuto.mlclk.mongodb.net/manual?retryWrites=true&w=majority&appName=ganuto # Test and assessment purpose, no need to worry XD
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy